sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mongodb
addons:
  code_climate:
    repo_token: 04927ee143de55b174e58ae380c7c6ec62d25f09f8bbca02bf1dc62e0152c2ad
script:
  - cd dummy
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=04927ee143de55b174e58ae380c7c6ec62d25f09f8bbca02bf1dc62e0152c2ad bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=04927ee143de55b174e58ae380c7c6ec62d25f09f8bbca02bf1dc62e0152c2ad bundle exec cucumber